### ISSUE TITLE
[base] Badge

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#1]
### 📝 Description

A badge is a visual indicator that communicates notifications, counts, or status information on/near an associated component. Badges can contain numbers or labels.

### 🎨 Design

![Image](https://github.com/user-attachments/assets/58a922ee-d973-4705-a599-704c0b30b6a6)
Figma: [❖ Components / Badge](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=17-162&m=dev)

### 🎯 Purpose & Use Cases

- Notification indicators: Showing counts of unread messages, notifications, etc.
- Status indicators: Displaying the state of an item (new, updated, deprecated, success, error)
- Categorization: Labeling content with categories or tags
- Highlighting: Drawing attention to new features or content
- Numeric counters: Displaying metrics, scores, or numerical values
- Progress indicators: Showing steps in a multi-step process (e.g., "1 of 3")
- Dot indicators: Small visual cues to indicate status without textual content
- Standalone badges: Used independently of other components to convey information
_Source: [RFC: 0001 - Badge](https://github.com/openui/design-system/pull/9/files?short_path=18a012d#diff-18a012dc8e98543769d12b271b7826aceafd89d1754931b948523ccc4a6a82f5)_ 

### 🔀 Variants & States

- Size: `large`, `medium`, `small`
- Color variations: TBD

### 🔄 Dependencies & Related Components

A badge can be used on several other components, possible options include but are not limited to:
- Button, e.g. shopping cart
- Link, especially in a navigation, e.g. news feed with unread messages
- Chips, especially filter chips, e.g. number of resulting items for this filter
- Tabs
- Accordions
 
### 🔮 Tokens

```yml
post-badge-bg: post-scheme-color-notification-badge-bg
post-badge-fg: post-scheme-color-notification-badge-fg
post-badge-stroke: post-scheme-color-notification-badge-stroke
post-badge-height-l: post-device-sizing-notification-1
post-badge-height-m: post-device-sizing-notification-2
post-badge-height-s: post-device-sizing-notification-3
post-badge-padding-inline-l: post-device-spacing-padding-7
post-badge-padding-inline-m: post-device-spacing-padding-8
```

### 🔗 References

- [Component Gallery Badge](https://component.gallery/components/badge/)
- [Open UI Badge Request for Comments](https://github.com/openui/design-system/pull/9/files?short_path=18a012d#diff-18a012dc8e98543769d12b271b7826aceafd89d1754931b948523ccc4a6a82f5)
