### ISSUE TITLE
[base] Popover

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#110]
### 📝 Description

An element that pops up from another element over other content; it differs from a tooltip in that it is usually triggered via click instead of hover and can contain interactive elements. [^1]

Semantically, popovers act as disclosure content which is not linked to the trigger. The trigger has an aria-expanded attribute to communicate the current state of the popover. [^2]

### 🎨 Design

[Popover Design in Figma](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=442-18156&m=dev)

### 🎯 Purpose & Use Cases

- Provide additional context to a data point or element
- Information preview on a link (like on wikipedia)
- Non modal (not blocking the page) form for editing content

### 🔀 Variants & States

- **Placement**: Different placement options provide flexibility. Default is "top". Available options are:
  - "bottom"
  - "bottom-end"
  - "bottom-start"
  - "left"
  - "left-end"
  - "left-start"
  - "right"
  - "right-end"
  - "right-start"
  - "top"
  - "top-end"
  - "top-start"
- **Arrow**: Can be displayed with or without an arrow pointing to the trigger element. Default is no arrow.
- **Width**: Popovers have a max-width that can be customised. Default is 280px.

### 🔄 Dependencies & Related Components

**Don't confuse the popover with**
- Tooltip: Gives icon buttons and other controls without descriptive text an accessible name and a visual description
- Menu: Contains a list of actions or links and provides additional keyboard navigation that the popover does not provide

### 🔮 Tokens

```yml
post-popover-bg: palette-accent-bg
post-popover-fg: palette-accent-fg
post-popover-border: palette-accent-border
post-popover-border-radius: default-border-radius

#@dev: might be best applied to a container within to enable edge-to-edge popover content
post-popover-padding: 8px
```

### 🔗 References

[^1]: Popover on the Component Gallery, https://component.gallery/components/popover/
[^2]: Previous discussion https://github.com/swisspost/design-system/issues/4595
