### ISSUE TITLE
[base] Tooltip

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#27]
### 🎨 Design

Design Figma: [🟡 Work in progress / Tooltip (section)](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=14016-23251&t=99tPzTW8YcAIs8XH-4)

### 🔮 Tokens

```yml
// Common
overlay-element.arrow.size: 8.5px // to create
overlay-element.arrow.border-radius: 2px // to create
overlay-element.arrow.border-width: 1px // post-border-width-alternative1

overlay-element.arrow.color.border: #ffffff (light mode) / #050400 (dark mode) // post.scheme.color.surface.accent.fg
overlay-element.arrow.color.bg: #373632 (light mode) / #fafafa (dark mode) // post.scheme.color.surface.accent.bg
overlay-element.elevation: 300 // post-core-elevation-3

// Tooltip
tooltip.padding.block: 2.5px // post-spacing-14
tooltip.padding.inline: 8px // post-spacing-15
tooltip.border-width: 1px // post-border-width-alternative1
tooltip.color.border: #fafafa (light mode) / #050400 (dark mode) // post.scheme.color.surface.accent.fg
tooltip.color.bg: #373632 (light mode) / #ffffff (dark mode) // post.scheme.color.surface.accent.bg
tooltip.color.fg: #ffffff (light mode) / #050400 (dark mode) // post.scheme.color.surface.accent.fg
tooltip.font-size: 14px // post-device-font-size-9
tooltip.border-radius: 4px // post-border-radius-1
```
