### ISSUE TITLE
[base] Tag

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#37]
### 🎨 Design

Figma: [🟡 Work in progress / Tags](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=14016-22633&t=p3juzUo6TsPmN0ak-4) (section)

### 🔀 Variants & States

- Sizes:
  - Large: For non-inline tagging
  - Small: For inline tagging 
- Icon:
  - Label with icon: For faster scanning through icon recognition
  - Label only: tbd

### 🔄 Dependencies & Related Components

- "Interactive tag" = [Chips](https://github.com/swisspost/design-system-planner/issues/94)

### 🔮 Tokens

```yml
# --- GENERIC ---
post-tag-border-style: solid
post-tag-border-width: 2px
post-tag-border-radius: 4px 

# Large
post-tag-large-height: 32px
post-tag-large-padding-inline: 8px
post-tag-large-gap-inline: 6px
post-tag-large-font-size: 16px # Label medium
post-tag-large-icon-size: 18px / 18px / 16px

# Small
post-tag-small-height: 24px
post-tag-small-padding-inline: 6px
post-tag-small-gap-inline: 6px
post-tag-small-font-size: 14px # Label small
post-tag-small-icon-size: 14px

# --- NEUTRAL ---
post-tag-neutral-color-fg: #050400 / #FFFFFF
post-tag-neutral-color-border: #050400 / #FFFFFF
post-tag-neutral-color-icon: #050400 / #FFFFFF

# --- SIGNAL ---
post-tag-info-color-fg: #050400
post-tag-info-color-bg: #BFD3E7
post-tag-info-color-border: #0050A1
post-tag-info-color-icon: #0050A1

post-tag-success-color-fg: #050400
post-tag-success-color-bg: #C3DDBF
post-tag-success-color-border: #107800
post-tag-success-color-icon: #107800

post-tag-warning-color-fg: #050400
post-tag-warning-color-bg: #F5CEBF
post-tag-warning-color-border-color: #D93D00
post-tag-warning-color-icon-color: #D93D00

post-tag-error-color-fg: #050400
post-tag-error-color-bg: #EBBFBF
post-tag-error-color-border: #B20000
post-tag-error-color-icon: #B20000

```

### 🔗 References

- [Tag component](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=11194-50777) in DS V1 (Figma)
- Tags = Non-interactive chips (as per Pattern Discussion, see https://github.com/swisspost/design-system/issues/5155)
