### ISSUE TITLE
[base] Stepper (horizontal)

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#42]
### 📝 Description

A stepper guides users through any linear, multistep process by showing the user their completed, current, and future steps in an interactive manner.

### 🎨 Design

Figma: [Foundations & Components / ❖ Components / Stepper](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=21-176)

### 🎯 Purpose & Use Cases

- [Pick @ home](https://www.post.ch/en/customer-center/online-services/rhe/pick-at-home/info)
- [PromoPost Quick Calculator](https://promopost.post.ch/ppm-client-qcpublic/qc/kampagneneckdaten)

### 🔀 Variants & States

- **Orientation**: Horizontal (default), Vertical (see #118)
- **Interactive navigation** (=navigation via click on indicator): 
  - Non-interactive: User can navigate one step back and one step forward via buttons "back" and "next"
  - Interactive: User can navigate to any step via click on step indicator (https://github.com/swisspost/design-system/issues/5497)

#### States (to be reviewed)
- **Open**: Step is still open
- **Active**: Current step
- **Complete**: Step is complete, user can go back to edit

### 🔄 Dependencies & Related Components
- https://github.com/swisspost/design-system-planner/issues/118

### 🔮 Tokens

```yml
# Type: color
post.stepper.text.enabled-fg: post.scheme.color.interactive.primary.enabled.fg1
post.stepper.text.disabled-fg: post.scheme.color.interactive.primary.disabled.fg1
post.stepper.enabled-bg: post.scheme.color.interactive.primary.enabled.bg2
post.stepper.enabled-fg: post.scheme.color.interactive.primary.enabled.fg3
post.stepper.completed-bg: post.scheme.color.interactive.primary.selected.bg2
post.stepper.hover-bg: post.scheme.color.interactive.primary.hover.bg2
post.stepper.hover-fg: post.scheme.color.interactive.primary.hover.fg3
post.stepper.disabled-bg: post.scheme.color.interactive.primary.disabled.bg4
post.stepper.disabled-fg: post.scheme.color.interactive.primary.disabled.fg3

post.stepper.connector.active: post.scheme.color.interactive.primary.enabled.fg1
post.stepper.connector.completed: post.scheme.color.interactive.primary.selected.bg2
post.stepper.connector.next: post.scheme.color.interactive.primary.disabled.bg4

post.stepper.enabled-stroke: post.scheme.color.interactive.primary.enabled.stroke3
post.stepper.completed-stroke: post.scheme.color.interactive.primary.selected.stroke3
post.stepper.hover-stroke: post.scheme.color.interactive.primary.hover.stroke3
post.stepper.disabled-stroke: post.scheme.color.interactive.primary.disabled.stroke3

# Type: spacing
post.stepper.gap.text-start: post.device.spacing.gap.1
post.stepper.gap.labels: post.device.spacing.gap.5
post.stepper.padding.connector: post.device.spacing.padding.9

# Type: borderRadius
post.stepper.border-radius.round: post.device.border-radius.round

# Type: sizing
post.stepper.indicator: post.device.sizing.interactive.stepper.indicator

# Type: borderWidth
post.stepper.border-width: post.device.border-width.default

# Type: fontSizes
post.stepper.step-label.font-size: post.device.font-size.7

# Type: fontWeights
post.stepper.step-label.selected.font-weight: post.device.font-weight.bold
```
