### ISSUE TITLE
[base] Number Input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#45]
### 📝 Description

A control for editing a numeric value with buttons for decrementing / incrementing. [^1]
fka. Spin button

### 🎨 Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=14016-18313&t=xQdJ3KtfCT99hmhK-4
( ↳ as section in page [🟡 Work in progress](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13943-50752) )

### 🎯 Purpose & Use Cases

- Shopping cart: update the quantity of items in the cart
- Inventory management

### 🔀 Variants & States

Reflects an [input with type number](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/number) with additional attributes and styleable control buttons.

- **min**: minimum value
- **max**: maximum value
- **step**: increase/decrease by this amount, can be a floating point number

### 🔄 Dependencies & Related Components

- Input type number
- Button

### 🔮 Tokens

```yml

# Input
post.number-input.color.enabled-bg: #FFF
post.number-input.color.enabled-fg: #050400
post.number-input.color.enabled-border: #050400
post.number-input.color.disabled-bg: #FFF 0%
post.number-input.color.disabled-fg: #696864
post.number-input.color.disabled-border: #696864
post.number-input.color.hover-bg: #FFF
post.number-input.color.hover-fg: #504f4b
post.number-input.color.hover-border: #504f4b

post.number-input.sizing.height: 64px / 56px / 56px
post.number-input.small.sizing.height: 48px / 40px / 40px

post.number-input.field.padding.block.start: 25.5px / 23px / 24.5px
post.number-input.field.padding.block.end: 4.5px / 5px / 6.5px
post.number-input.field.padding.inline: 14px

post.number-input.small.field.padding.block: 7px / 6px / 7.5px
post.number-input.small.field.padding.inline: 14px

# Border
post.number-input.border-radius: 4px
post.number-input.border-width: 2px
post.number-input.border.style.default: solid
post.number-input.border.style.disabled: dashed

# Action button
post.number-input.action-button.icon.size: 32px
post.number-input.action-button.padding.inline: 11px / 7px / 7px
post.number-input.action-button.padding.block: 14px / 10px / 10px
post.number-input.action-button.elevation: 100

post.number-input.small.action-button.padding.inline: 7px / 3px / 3px
post.number-input.small.action-button.padding.block: 6px / 2px / 2px

# Label
post.number-input.label.padding.block.start: 4.5px / 5px / 6.5px
post.number-input.label.padding.inline.start: 14px 
post.number-input.label.padding.inline.end: 8px
post.number-input.label.font.size: 14px / 12px / 12px

# Validation
post.number-input.validation.icon.size: 24px
post.number-input.validation.icon.padding.block: 18px / 14px / 14px
post.number-input.validation.icon.padding.inline.end: 14px

post.number-input.small.validation.icon.padding.block: 10px / 6px / 6px

```

### 🔗 References

- Experimental reference implementation: https://codepen.io/tuelsch/pen/raNjRXy

[^1]: https://component.gallery/components/stepper/
