### ISSUE TITLE
[base] Radio Button

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#57]
### 🔮 Tokens

```yml

# RADIO BUTTON SMALL

# ❖ _Radio button small / Icon
post.radio-button.small.icon.size: post.device.sizing.interactive.icon.size4 # 16 / 16 / 16
post.radio-button.small.icon.dot: post.device.sizing.icon.8 # 8 / 8 / 8
post.radio-button.small.icon.padding: post.device.spacing.padding.13 # 0 / 0 / 0

# ❖ Radio button small
post.radion-button.small.icon.container.padding: post.device.spacing.padding.14 # 2.5 / 2.5 / 2.5
post.radion-button.small.padding.block: post.device.spacing.padding.21 # 1.5 / 1.5 / 1.5
post.radion-button.small.label.padding.block: post.device.spacing.padding.13 # 0 / 0 / 0

# ❖ Radio button group small / Vertical & Horizontal
post.radio-button.padding.block.group: post.device.spacing.padding.block.8 # 8 / 8 / 4
post.radio-button.small.group.gap.block: post.device.spacing.gap.9 # 12 / 12 / 10

# ❖ Radio button group small / Vertical
post.radio-button.small.group.items.gap.block: post.device.spacing.gap.1 # 8 / 8 / 8

# ❖ Radio button group small / Horizontal
post.radio-button.small.group.items.gap.inline: post.device.spacing.gap.10 # 24 / 24 / 16

```
