### ISSUE TITLE
[base] Progressbar

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#60]
### 🎨 Design

Figma: [🟡 Work in progress / Components / Progress bar](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13997-41298&t=mln0ljqDd9chdZWV-4) (section)

### 🔄 Dependencies & Related Components

- File upload

### 🔮 Tokens

```yml

# COLORS
post.progressbar.color.fg: '#050400 / #FFFFFF' # post.scheme.color.body.fg
post.progressbar.track.color.stroke: '#050400 / #FFFFFF' # post.scheme.color.interactive.primary.enabled.stroke

post.progressbar.status.color.neutral: '#050400 / #FFFFFF' # post.scheme.color.interactive.primary.enabled.bg2
post.progressbar.status.color.success: '#107800 / #55E543' # post.scheme.color.signal.success-solo
post.progressbar.status.color.warning: '#D93D00 / #FF8D13' # 🆕 post.scheme.color.signal.warning-solo
post.progressbar.status.color.error: '#B20000 / #FF7575' # 🆕 post.scheme.color.signal.error-solo

# SEMANTIC COLORS
🆕 post.scheme.color.signal.info-solo: 
  ↳ post.core.color.notification.blue: '#0050A1'
  ↳ 🆕 post.core.color.notification.blue-night: '#D6EDFF'

🆕 post.scheme.color.signal.warning-solo: 
  ↳ post.core.color.notification.orange: '#D93D00'
  ↳ 🆕 post.core.color.notification.orange-night: '#FF8D13'

post.scheme.color.signal.error-solo:
  ↳ post.core.color.notification.red: '#B20000'
  ↳ 🆕 post.core.color.notification.red-night: '#FF7575' # Value changes from #FFC2C2 to #FF7575

# SIZING
post.progressbar.icon.size: 16 / 16 / 16 # post.device.sizing.notification.2
post.progressbar.indicator.size.height: 16 / 16 / 16 # 🆕 post.device.sizing.interactive.progressbar.indicator

# SPACING
post.progressbar.gap.inline.start: 8 / 8 / 8 # post.device.spacing.gap.inline.8
post.progressbar.gap.inline.end: 16 / 16 / 16
post.progressbar.gap.block: 8 / 8 / 8 # post.device.spacing.gap.8
post.progressbar.assistive-area.gap.block: 4 / 4 / 4 # 🆕 post.device.spacing.gap.13

# BORDER
post.progressbar.indicator.border-width: 1 / 1 / 1 # post.device.border-width.alternative1
post.progressbar.indicator.border-radius: 100 # post.device.border-radius.round

# TYPOGRAPHY
post.progressbar.label.font-size: 16 / 16 / 14 # post.device.font-size.7
post.progressbar.label.font-weight: Bold (700) # post.device.font-weight.bold
post.progressbar.sublabel.font-size: 14 / 14 / 14 # post.device.font-size.9

# OTHER
post.progressbar.indicator.border-style: Solid # post.core.border-style.solid

```

### 🔗 References

- Figma: [Progressbar](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=16729-53257) (V1)
