### ISSUE TITLE
[base] Pagination

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#62]
### 🎨 Design

Figma: 
- [Foundations & Components / Pagination](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=27578-183756)
- [Foundations & Components / 🔴 Backlog / Table pagination](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=27562-126599&t=HRjNa3WzRMuBqTIe-4) (section)

### 🔀 Variants & States

- **Pagination**: 
  - For unsortable and therefore unpredictable (= not possible for user to estimate on which page a certain entry can be found) 
  - Medium to large sized datasets 
- **Table pagination**:
  - For sortable and/or predictable (= possible for user to estimate on which page a certain entry can be found)
  - Large sized datasets 

### 🔮 Tokens

```yml
# PAGINATION (final)
post.pagination.number.size: 48px / 40px / 32px # post.device.sizing.interactive.button.height.1

post.pagination.numbers.gap: 4px # post.device.spacing.gap.inline.4
post.pagination.gap: 16px / 16px / 12px # to create: post.device.spacing.gap.11
post.pagination.padding: 8px # post.device.spacing.padding.15

post.pagination.number.font-weight: bold # post.device.font-weight.bold
post.pagination.number.font-size: 20px / 16px / 14px # post.device.font.size.6

post.pagination.number.border-radius: 100 # post.device.border-radius.round
post.pagination.number.border-width: 2px # post.device.border-width.default
post.pagination.page-number.border-style: solid

post.pagination.number.color.enabled-fg: '#050400 / #ffffff' # post.scheme.color.interactive.primary.enabled.fg1
post.pagination.number.color.enabled-bg: 'transparent / transparent' # to create:  post.scheme.color.interactive.primary.enabled.bg4
post.pagination.number.color.enabled-stroke: 'transparent / transparent' # to create:  post.scheme.color.interactive.primary.enabled.stroke5
post.pagination.number.color.hovered-fg: '#504F4B / #ffffff' # post.scheme.color.interactive.primary.hover.fg1
post.pagination.number.color.hovered-bg: 'transparent / transparent' # to create:  post.scheme.color.interactive.primary.hover.bg5
post.pagination.number.color.hovered-stroke: '#504F4B / #ffffff' # post.scheme.color.interactive.primary.hover.stroke

post.pagination.number.color.selected.enabled-bg: '#050400 / #fff' # post.scheme.color.interactive.primary.selected.bg4
post.pagination.number.color.selected.enabled-fg: '#fff /#050400' # post.scheme.color.interactive.primary.selected.fg3
post.pagination.number.color.selected.enabled-stroke: '#050400 / #fff' # post.scheme.color.interactive.primary.selected.stroke1
post.pagination.number.color.selected.hovered-bg: '#504F4B / #fff' # post.scheme.color.interactive.primary.hover.bg2
post.pagination.number.color.selected.hovered-fg: '#fff / #504F4B' # post.scheme.color.interactive.primary.hover.fg3
post.pagination.number.color.selected.hovered-stroke: '#fff / #504F4B' # post.scheme.color.interactive.primary.hover.stroke



# TABLE PAGINATION (to be reviewed by dev)
pagination.table.items-per-page.gap: 16px // post.device.spacing.gap.7
pagination.table.label.font-size: 16px 16px 14px // post.device.font-size.7
pagination.table.page-nav.gap: 16px 16px 12px // to create: post.device.spacing.gap.11
pagination.table.page-nav.arrows.gap: 8px // post.device.spacing.gap.1
pagination.table.page-nav.total-pages.gap: 12px 12px 8px // to create: post.device.spacing.gap.12
```

**Note:**
There are very few tokens as most elements of the pagination are existing button/form components:
- `Pagination arrows` → Icon button secondary medium
- `Table pagination arrows` → Icon button tertiary small
- `Table pagination select` → Select small (not yet developed)
- `Table pagination input` → Input small (not yet developed)

### 🔗 References

- Figma: [Design System V1 / Pagination](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=16523-53293)
