### ISSUE TITLE
[base] Notification (inline)

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#63]
### 📝 Description

Inline notifications show up in task flows, to communicate the users the status of an action or system. It can also be used as a persistent element on the page to communicate information which needs higher attention than regular text. Inline notifications show up in task flows, to communicate the users the status of an action or system. It can also be used as a persistent element on the page to communicate information which needs higher attention than regular text. 

### 🎨 Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=1447-8953&m=dev

#### Status

- Information
- Success
- Warning
- Error
- ~Neutral~ // Removed as per 18-Aug-2025, --> [#6023](https://github.com.mcas.ms/swisspost/design-system/issues/6023?McasTsid=11760&McasCtx=4)

### 🔄 Dependencies & Related Components

- Notification_Message / Process notfication in V1

### 🔮 Tokens

```yml
## Info
post.inline-notification.info.color.stroke: '#0050A1'
post.inline-notification.info.color.bg: '#BFD3E7'

## Success
post.inline-notification.success.color.stroke: '#107800'
post.inline-notification.success.color.bg: '#C3DDBF'

## Warning
post.inline-notification.warning.color.stroke: '#D93D00'
post.inline-notification.warning.color.bg: '#F5CEBF'

## Error
post.inline-notification.error.color.stroke: '#B20000'
post.inline-notification.error.color.bg: '#EBBFBF'

# SIZING
post.inline-notification.icon.size: 32
post.inline-notification.min-width: 297
post.inline-notification.max-width: 600

# SPACING
post.inline-notification.gap: 8
post.inline-notification.padding.block: 10
post.inline-notification.padding.inline: 14
post.inline-notification.multiline.icon.margin-block-start: 2
post.inline-notification.multiline.content.margin-inline-start: 40

# BORDER
post.inline-notification.border-width: 2
post.inline-notification.border-radius: 4
post.inline-notification.border-style: Solid
```

### 🔗 References
<!-- Add references to other Design Systems that implement this component, for example from the [component gallery](https://component.gallery/)
