### ISSUE TITLE
[base] Dialog

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#64]
### 📝 Description

A dialog is an interface element that appears over other content. It requires an interaction from the user before they can return to whatever is underneath. [^1]

It's usually centered on the screen, unlike a popover that is anchored to the triggering element, with  a blackened or blurred out background.

### 🎨 Design

Figma: [🟡 Work in progress / Components / Dialog](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13997-35947&t=FevhJUxtTFV9imfS-4) (section)

### 🎯 Purpose & Use Cases

- User needs to take a decision before proceeding
- Confirmation of action
- In-page forms for updating data without leaving the page

#### Width
- **Small**: smaller max-width
- **Default**: Medium width
- **Large**: Almost screen-filling

### 🔮 Tokens

```yml
# COLORS
post.dialog.color.fg: '#050400 / #FFFFFF' # post.scheme.color.body.fg
post.dialog.color.bg: '#FAFAFA / #373632' # post.scheme.color.body.bg
post.dialog.color.stroke: '#B4B3AF (Sandgrey.030) / #B4B3AF (Sandgrey.030)' # post.scheme.color.interactive.primary.enabled.stroke4

post.backdrop.color.bg: Sandgrey 100 (#050400), opacity 80% # 🆕 post.scheme.color.backdrop.bg
post.backdrop.blur: 10 # post.core.dimension.10

# SIZING
post.dialog.icon.size: 40 / 32 / 28 # 🆕 post.device.sizing.notification.icon.5

# SPACING
post.dialog.gap.inline: 24 / 24 / 16 # post.device.spacing.gap.10
post.dialog.padding.block.start: 24 / 24 / 16 # post.device.spacing.padding.block.25
post.dialog.padding.block.end: 24 / 24 / 24 # 🆕 post.device.spacing.padding.31
post.dialog.padding.inline: 24 / 24 / 16 # post.device.spacing.padding.20
post.dialog.content.gap.block: 24 / 24 / 16 # post.device.spacing.gap.10
post.dialog.footer.actions.gap: 8 / 8 / 8  # post.device.spacing.gap.8 (Horizontal (Desktop, Tablet) and vertical (Mobile))

# BORDER
post.dialog.border-width: 2 px # post.device.border-width.default
post.dialog.border-radius: 8 px # post.device.border-radius.2
post.dialog.border-style: Solid # post.core.border-style.solid

# ELEVATION / BOX SHADOW
post.dialog.elevation: Elevation 500 # post.device.elevation.500

# TYPOGRAPHY
post.dialog.heading.font-size: 36 / 32 / 28 # post.device.font-size.2
post.dialog.heading.font-weight: Extrablack (950) # post.device.font-weight.extra-black
post.dialog.content.font-size: 20 / 16 / 14 # post.device.font-size.6 (paragraph m)

```

### 🔗 References

- Figma: [Dialog component V1](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=16696-55910)

[^1]: https://component.gallery/components/modal/
