### ISSUE TITLE
[base] Divider

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#90]
### 📝 Description

A separator between two elements, usually consisting of a horizontal line. [^1] \<hr\> Element styles

### 🎨 Design

Figma: [🟡 Work in progress / Components / Divider](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13995-180113&t=ECcGEZv3qpv6gwDe-4) (section)

### 🎯 Purpose & Use Cases

To separate/group content

### 🔀 Variants & States

- Spacing top and bottom can be selected independently. Options: 0 px, 4 px, 8 px, 16 px, 32 px, 40 px 

### 🔄 Dependencies & Related Components

No dependency, but thematically related:
- https://github.com/swisspost/design-system-planner/issues/9
- https://github.com/swisspost/design-system-planner/issues/76

### 🔮 Tokens

```yml
post.divider.margin.block: 8px # References post.utility.margin . Default value = 8px
post.divider.border-width: 2px
post.divider.border: #696864 (Sandgrey 060) (Light) / #82817D (Sandgrey 050) (Dark)
```

### 🔗 References

[^1]: https://component.gallery/components/separator/
