### ISSUE TITLE
[base] Checkbox

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system-planner#95]
### 🎨 Design

Figma: [Components / Checkbox ](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=18-14)(default and small)

### 🔀 Variants & States

- Default (for web)
- Small/Compact (for applications / compact)

### 🔮 Tokens

```yml

# CHECKBOX SMALL

# ❖ _Checkbox / Icon small
post.checkbox.small.icon.size: post.device.sizing.interactive.icon.size4 # 16 / 16 / 16
post.checkbox.small.icon.padding: post.device.spacing.padding.13 # 0 / 0 / 0

# ❖ Checkbox small
post.checkbox.small.icon.container.padding: post.device.spacing.padding.14 # 2.5 / 2.5 / 2.5
post.checkbox.small.padding.block: post.device.spacing.padding.21 # 1.5 / 1.5 / 1.5
post.checkbox.small.label.padding.block: post.device.spacing.padding.13 # 0 / 0 / 0

# ❖ Checkbox group small / Vertical & Horizontal
post.checkbox.group.padding.block: post.device.spacing.padding.block.8 # 8 / 8 / 4
post.checkbox.small.group.gap.block: post.device.spacing.gap.9 # 12 / 12 / 10

# ❖ Checkbox group small / Vertical
post.checkbox.small.group.items.gap.block: post.device.spacing.gap.1 # 8 / 8 / 8

# ❖ Checkbox group small / Horizontal
post.checkbox.small.group.items.gap.inline: post.device.spacing.gap.10 # 24 / 24 / 16

```
